name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main  # Trigger on pushing to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use an Ubuntu environment for the job

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}   # Docker username from GitHub secrets
        password: ${{ secrets.DOCKER_PASSWORD }}   # Docker password from GitHub secrets

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .  # Current directory where your Dockerfile is located
        push: true   # Push the image to Docker Hub after building
        tags: harineemd/web-app:latest  # Tag for your Docker image
